### ISSUE TITLE
wallpapers.json fix

### ISSUE THREAD

**Issue by vaimalaviya1233** [VigneshVicky003/Coves_KWGT#1]
you should use https://gist.github.com/ gist to host and make it anonymous to stop anyone else using wallpapers elsewhere
hopefully not many dev knows this but this might help you😊👍
there is also file upload option so you can surely delete this repo and use gist to create secrete repo that only allowed when you give url of that repo👍

**Comment by VigneshVicky003** [comment]
wow thanks. I didn't know about that before. thanks for your help

**Comment by VigneshVicky003** [comment]
> you should use https://gist.github.com/ gist to host and make it anonymous to stop anyone else using wallpapers elsewhere
> hopefully not many dev knows this but this might help you😊👍
> there is also file upload option so you can surely delete this repo and use gist to create secrete repo that only allowed when you give url of that repo👍

Since I'm new to GitHub, it's hard for me to understand. Like you said not many devs know about this, so I don't get any help on that. If you know how to do that, please guide me to do that.
It would be so much helpful to me🙏
You can contact me at👇
Telegram : https://t.me/vignesh_vicky_003
Instagram : https://instagram.com/vignesh_vicky__003
Twitter : https://twitter.com/VigneshVickyGVK
